### ISSUE TITLE
hello M BUISSON

### ISSUE THREAD

**Issue by vcenter6user** [MathieuBuisson/Powershell-VMware#3]
Hello M BUISSON,
First excuse for my English i m french.
I'm using your script Get-StorageViewsReport.psm1 to getting a snapshot state for every VM in our VCENTER and we send the result by mail.
All is working fine since several years and i must thanks you for you work and sharing you knowledge.

The problem is that we have create a new DATA CENTER in our VCENTER console with a new CLUSTER inside. 
And now the script you developped is no more working 
. I try to find why but my knowledge are limited

![clust](https://user-images.githubusercontent.com/29622832/27433980-32c3caac-5757-11e7-892c-bee559563e25.png)

below  the command that we use and that was working fine before creating the 2de Datacenter/cluster

#collect vm snaphot info to text file verifsnapshot.txt
****Get-VM | Get-StorageViewsReport** | Sort-Object -Property VM | Format-Table -auto | out-file C:\Users\administrateur\Desktop\snapshot_report\verifsnaphot.txt -encoding UTF8 -width 100**

The error is probably a problem with the datastore Type (NAS -NFS simplivity) for the second cluster we have created
![nas](https://user-images.githubusercontent.com/29622832/27433545-7f7fede6-5755-11e7-8455-3890cb9afcfa.JPG)

thanks if you could have time to see why you script is no more working with this new Datastore in NAS type 
(I have tested the last version of your script after you patched it for NAS support but it dontt work too)
Thanks
**********************************************************************
Finally when i suppress the code below (by datastore option) because i d'ont use it i use by-vm (get-vm)
it works.
***old version script***** don't works like say drockwood94  22 jull 2015 in old comment
**[Parameter(ParameterSetName='ByDatastore')]
        [switch]$ByDatastore,

        [Parameter(ValueFromPipeline = $True,
        ParameterSetName='ByDatastore',
        ValueFromPipelineByPropertyName=$True,Position=0)]   
        [VMware.VimAutomation.ViCore.Impl.V1.DatastoreManagement.VmfsDatastoreImpl[]]$Datastore = (Get-Datastore),**

******** in your patched code i have to suppress this code below too**** to works
 [Parameter(ParameterSetName='ByDatastore')] 
84         [switch]$ByDatastore, 
85 
 
86         [Parameter(ValueFromPipeline = $True, 
87         ParameterSetName='ByDatastore', 
88         ValueFromPipelineByPropertyName=$True,Position=0)]    
89         [ValidateScript({ $_[0] -is [VMware.VimAutomation.ViCore.Impl.V1.DatastoreManagement.VmfsDatastoreImpl] -or $_[0] -is [VMware.VimAutomation.ViCore.Impl.V1.DatastoreManagement.NasDatastoreImpl] })] 
90         $Datastore = (Get-Datastore),

**Comment by MathieuBuisson** [comment]
Hi @vcenter6user ,

I won't be able reproduce (and therefore debug) this issue as I don't have access to any vSphere environment anymore.

Sorry I can't help.

**Comment by vcenter6user** [comment]
hi M Buisson,
Thanks for your message. It doesn't matter, the workaroud work so i can still use your script with disabling the "bydatastore fonction/variable" that i d'ont need.
thanks
